In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [17]:
import numpy as np

a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
import numpy as np

arr = np.array([1 , 2 , 3  ,4] , ndmin = 5)
print(arr)
print("number of dimensions:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [21]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row:', arr[1,4])

5th element on 2nd row: 10


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[:3])
print(arr[2:])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[2::-1])

[2 3 4 5]
[1 2 3]
[3 4 5 6 7]
[5 6]
[2 4]
[3 2 1]


In [32]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
[1 2 3 4]
int32


In [37]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [43]:
import numpy as np
arr = np.array([1,0.1,3.1])
newarr = arr.astype('c')
print(newarr)
print(newarr.dtype)

[b'1' b'0' b'3']
|S1


In [41]:
import numpy as np
arr = np.array([1,2,0])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True False]
bool


In [44]:
import numpy as np
arr = np.array([1,2,3,4,5])
x=arr.copy()
arr[1]=77
print(arr)
print(x)

[ 1 77  3  4  5]
[1 2 3 4 5]


In [45]:
import numpy as np
arr = np.array([1,2,3,4,5])
x=arr.view()
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [46]:
import numpy as np
arr = np.array([1,2,3,4,5])
x=arr.view()
x[0]=31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [48]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [51]:
import numpy as np
arr = np.array([1,2,3,4,5],ndmin=5)
x=arr.view()
print(arr)
print('Shape of array is:',arr.shape)

[[[[[1 2 3 4 5]]]]]
Shape of array is: (1, 1, 1, 1, 5)


In [52]:
#Array Reshape
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = arr.reshape(4,3)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [53]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=arr.reshape(2,3,2)
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [54]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = arr.reshape(2,2,-1)
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [59]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
x = arr.reshape(-1)
print(x)

[1 2 3 4 5 6]


In [60]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [61]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [62]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [63]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [64]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [65]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [68]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr[:, ::3]):
  print(x)

1
2
3
7
8
9


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([[1, 2 ,3 ,4],[5 ,6 ,7 ,8]])

for 

In [69]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [70]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [86]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=-1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [72]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [73]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [74]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [87]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [88]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [89]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [90]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [91]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [92]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
